package main

import (
	echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware
	_ "github.com/muhammadardie/echo-cms/docs" // docs generated by Swag CLI
	"github.com/muhammadardie/echo-cms/middleware"
	"github.com/muhammadardie/echo-cms/routes"
	
)


// @title Swagger Example API
// @version 1.0
// @description Conduit API
// @title Conduit API

// @host 127.0.0.1:8585
// @BasePath /api
	
// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {
	r := middleware.New()

	// swagger 
	r.GET("/swagger/*", echoSwagger.WrapHandler)

	g := r.Group("/api")

	routes.Register(g)

	r.Logger.Fatal(r.Start(":8080"))
}
